config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :points
    resources :answers
  end

  resources :user_follows

  resources :activities, only: [:index]

  root 'questions#index'

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users, only: [:show]
  post 'users/update_activities_last_viewed'

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :points
	accepts_nested_attributes_for :points, :reject_if => :all_blank, :allow_destroy => true
	has_many :answers
	accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @questions = Question.all
    respond_with(@questions)
  end

  def show
    if params[:user_id]
      @user_filtered_to = User.find(params[:user_id])
    else
      if signed_in?
        @user_filtered_to = current_user
      end
    end
    if params[:question_id_from]
      @question_from = Question.find(params[:question_id_from])
    end


    respond_with(@question)
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    @question.save
    respond_with(@question)
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      # REVIEW - Not sure this is the safest way.
      params.require(:question).permit(:user_id, :title, points_attributes: [:id, :_destroy, :title, :answer_id, :user_id], answers_attributes: [:id, :_destroy, :title, :user_id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_fields.html.erb
<div class="nested-fields">
	  <div class="well">

<%= f.input :title, as: :text, input_html: { rows: "5" }, label: 'Answer:' %> 
<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
<%= link_to_remove_association "Delete", f, :class => "btn btn-danger" %>
</div>
</div>

app/views/questions/_form.html.erb
<%= simple_form_for(@question, html: {class: 'form-vertical' }) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <%= f.input :title, label: 'Question:' %>

  <br>
  <br>


  <%= f.simple_fields_for :points, @question.points.where(user: current_user) do |point| %>

    <%= render 'point_fields', :f => point %>

    <br>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'Add Point', f, :points, :class => "btn btn-success" %>
  </div>

  <br>
  <br>


  <%= f.simple_fields_for :answers, @question.answers.where(user: current_user)  do |answer| %>

    <%= render 'answer_fields', :f => answer %>

    <br>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'Add Answer', f, :answers, :class => "btn btn-success" %>
  </div>

  <br>
  <br>
  <br>

  <div class="actions">
    <%= f.submit 'Save My Response', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/questions/_point_fields.html.erb
<div class="nested-fields">
		  <div class="well">

<%= f.input :title, as: :text, input_html: { rows: "5" }, label: 'Point:' %> 
<%= f.input :answer_id, collection: Answer.all.where(user: current_user), label: 'Answer (Optional):' %>
<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
<%= link_to_remove_association "Delete", f, :class => "btn btn-danger" %>
</div>
</div>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-7">

    <div class="page-header">
      <h1>Questions</h1>      
    </div>

    <div class="row">
      <div class="col-md-9">
        <% @questions.each do |question| %>
            <h3><%= link_to question.title, question %></h3>
            <br>
        <% end %>
      </div>
      <div class="col-md-3">
        <br>
        <%= link_to 'New Question', new_question_path, :class => "btn btn-success pull-right" %>
      </div>
    </div>


    </div>
    <div class="col-md-1">
    </div>

    <div class="col-md-4">


      <div class="page-header">
        <h1>Users</h1>
      </div>





  <br>
  <% if signed_in? %>
    <div id="follow-status">
      <% User.all.each do |user| %>



<div class="media">

  <div class="row">

    <div class="col-md-8">

      <div class="media-left media-middle">
        <a href="#">
          <img class="media-object img-circle" src=<%= user.twitter.image %>  style="width:36px;height:36px;border:0" alt="">
        </a>
      </div>


      <div class="media-body">
        <h4 class="media-heading" style="line-height: 36px;"><%= link_to "@" + user.twitter.nickname.downcase, user_path(user) %> </h4>
      </div>

    </div>
    <div class="col-md-4">

            <% if current_user.followed_users.include?(user) %>
          <%= simple_form_for current_user.user_follow_for_followed_user(user), method: :delete do |form| %>
            <div class="form form-actions pull-right">
              <%= submit_tag "Unfollow", class: 'btn btn-danger' %>
            </div>
          <% end %>
        <% else %>
          <%= link_to "Follow", new_user_follow_path(followed_user_id: user.id), :class => "btn btn-primary pull-right" %>
        <% end %>



    </div>

  </div>


</div>








        <br>
      <% end %>
    </div>
  <% end %>





  </div>
</div>




  <br>
  <br>
  <br>
  <br>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<script type="text/javascript">
  $(document).ready(function(){


function getUrlParameter(sParam)
{
    var sPageURL = window.location.search.substring(1);
    var sURLVariables = sPageURL.split('&');
    for (var i = 0; i < sURLVariables.length; i++) 
    {
        var sParameterName = sURLVariables[i].split('=');
        if (sParameterName[0] == sParam) 
        {
            return sParameterName[1];
        }
    }
}          



  var should_fade = $("#question-holder").is(":visible"); 

  if (!should_fade) {

    var question_back = getUrlParameter('question_back');

    if (question_back) {

        $("#question-holder").css('top', "30px");
        $('#question-holder').fadeIn({queue: false, duration: 500});
        $('#question-holder').animate({ top: "0px" }, 500);
         
    }
    else {
        $("#question-holder").css('top', "-30px");
        $('#question-holder').fadeIn({queue: false, duration: 500});
        $('#question-holder').animate({ top: "0px" }, 500);
         
         setTimeout(function () {
            $('#footer').fadeIn({queue: false, duration: 500});
          }, 300);
    }

}

    $( "#from-question" ).click(function( ev ) {
      ev.preventDefault();
      var href = $(this).attr('href');
      console.log(href)
      $('#question-holder').fadeOut({queue: false, duration: 500});
      $('#question-holder').animate({ top: "30px" }, 500);

     setTimeout(function () {
         window.location.href = href; //will redirect to your blog page (an ex: blog.html)
      }, 500); //will call the function after 2 secs.


    });

    $( "#to-question" ).click(function( ev ) {
      ev.preventDefault();
      var href = $(this).attr('href');
      console.log(href)
      $('#footer').fadeOut({queue: false, duration: 500});
      $('#question-holder').fadeOut({queue: false, duration: 500});
      $('#question-holder').animate({ top: "-30px" }, 500);

     setTimeout(function () {
         window.location.href = href; //will redirect to your blog page (an ex: blog.html)
      }, 500); //will call the function after 2 secs.


    });


  })
</script>


<div class="row">
  <div class="col-md-1">
  </div>

  <div class="col-md-10">

    <% if @question_from %>
      <div hidden class="" id="question-holder" style="position:absolute;">
    <% elsif params[:question_back] %>
      <div hidden class="" id="question-holder" style="position:absolute;">
    <% else %>
      <div class="" id="question-holder" style="position:absolute;">
    <% end %>

      <div class="page-header" id="page-header">
        <h1><%= @question.title %></h1>            

        <div class="row">
          <div class="col-md-2">
            <br>
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true" style="width:100%">
                <img src=<%= @user_filtered_to.twitter.image%> class="img-circle" alt="" style="width:36px;height:36px;border:0">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" >
                <% if @user_filtered_to.id != current_user.id %>
                  <li><%= link_to question_path(@question, user_id: current_user.id), :class => "button small-button green-button" do %><h4><img src=<%= current_user.twitter.image%> class="img-circle" alt="" style="width:36px;height:36px;border:0"> @<%= current_user.twitter.nickname.downcase%></h4><% end %></li>
                <% end %>
                <% current_user.followed_users.each do |user| %>
                    <% if @user_filtered_to != user %>
                      <% if current_user.id != user.id %>
                        <li><%= link_to question_path(@question, user_id: user.id), :class => "button small-button green-button" do %><h4><img src=<%= user.twitter.image%> class="img-circle" alt="" style="width:36px;height:36px;border:0"> @<%= user.twitter.nickname.downcase%></h4><% end %></li>
                      <% end %>
                    <% end %>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="col-md-1">
            <% if @user_filtered_to.id == current_user.id %>
            <br>
            <%= link_to edit_question_path(@question), :class => "button " do %><span class="glyphicon glyphicon-pencil" style="width:36px; height:50px; font-size:36px; line-height: 50px;"></span><% end %>
            <% end %>            
          </div>
        </div>
        <br>
      </div>

      <br>
      <% @user_filtered_to.points.where(question: @question).each do |point| %>
        <% if point.answer %>

          <div class="row">
            <div class="col-md-1">
              <span class="glyphicon glyphicon-arrow-down" style="width:36px; height:50px; font-size:36px; line-height: 50px;"></span>
            </div>
            <div class="col-md-11">
              <span style="font-size:18px; font-weight: bold;">
                <%= link_to point.answer.title, question_path(point.answer.question, user_id: @user_filtered_to.id, question_id_from: @question.id), id: "from-question" %>
              </span>
              <br>
              <br>
              <span style="font-size:18px;">
                <%= point.title %>
              </span>
            </div>
          </div>

          <br>
          <br>
          <br>
        <% else %> 


          <div class="row">
            <div class="col-md-1">

              <span class="glyphicon glyphicon glyphicon-arrow-right" style="width:36px; height:50px; font-size:36px; line-height: 50px;"></span>

            </div>
            <div class="col-md-11">
              <span style="font-size:18px;">
                <%= point.title %>
              </span>
            </div>
          </div>


          <br>
          <br>
          <br>
        <% end %>
      <% end %>


      <% @user_filtered_to.answers.where(question: @question).each do |answer| %>


          <div class="row">
            <div class="col-md-1">

              <span class="glyphicon glyphicon glyphicon glyphicon-eye-open" style="width:36px; height:50px; font-size:36px; line-height: 50px;"></span>

            </div>
            <div class="col-md-11">
              <span style="font-size:18px; font-weight:bold;">
                <%= answer.title %>
              </span>
            </div>
          </div>



        <br>
      <% end %>

      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br> 
      <br>
      <br>
    </div>
  </div>
</div>

</div>

<% content_for :footer do %>

<% if @question_from %>
  <footer hidden class="footer footer-fixed-bottom" id="footer">

    <div class="container">
              <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-1">
                  <span class="glyphicon glyphicon glyphicon glyphicon-arrow-down" style="width:36px; height:50px; font-size:36px; line-height: 70px; color:#FFFFFF;"> </span>

                </div>
                <div class="col-md-10" style="padding-left: 0px;">
                  <span style="font-size:20px;  color:#FFFFFF; height:70px; line-height: 70px;">
                    <%= link_to @question_from.title, question_path(@question_from, user_id: @user_filtered_to.id, question_back: true), style: 'color:#FFFFFF;', id: "to-question"  %>
                  </span>
                </div>
    </div>
  </footer>

<% end %>
<%end%>