config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :points
    resources :answers
  end

  resources :user_follows

  resources :activities, only: [:index]

  root 'questions#index'

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users, only: [:show]
  post 'users/update_activities_last_viewed'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  devise :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable

  has_many :questions
  has_many :answers
  has_many :points
  has_many :user_follows
  has_many :followed_users, through: :user_follows
  has_many :activities
  has_many :identities

  def twitter
    identities.where( :provider => "twitter" ).first
  end

  def update_activities_last_viewed
    self.update_column(:activities_last_viewed, Time.now)
  end

  def activities_count
    Activity.for_user(self, current_user_id_for_since: self.id).count
  end

  def user_follow_for_followed_user(followed_user)
    user_follows.each do |user_follow|
      if user_follow.followed_user == followed_user
        return user_follow
      end
    end
  end

  def create_activity(item, action)
    activity = activities.new
    activity.targetable = item
    activity.action = action
    activity.save
    activity
  end

  def email_verified?
    self.email.length > 0
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

  def show
    @user = User.find(params[:id])

    questions = Array.new

    @user.points.each do |point|
      unless questions.include?(point.question)
        questions << point.question
      end
    end
    @user.answers.each do |answer|
      unless questions.include?(answer.question)
        questions << answer.question
      end
    end

    @questions_answered = questions


  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        # sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  def test
    respond_to do |format|
      format.json { head :no_content }
    end

  end

  def update_activities_last_viewed
      logger.debug "This is from debug"

    current_user.update_activities_last_viewed
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/finish_signup.html.erb
<div class="row">
<div id="add-email" class="container">
    <div class="page-header">
      <h1>Complete Profile</h1>      
    </div>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'email@me.com' %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
  <div class="row">

	  <div class="col-md-12">
		  <div class="page-header">
		    <h1>@<%= @user.twitter.nickname.downcase %></h1>
		  </div>

			<% if signed_in? %>
				<div id="follow-status">
					<% if current_user.followed_users.include?(@user) %>
						<%= simple_form_for current_user.user_follow_for_followed_user(@user), method: :delete do |form| %>
							<div class="form form-actions">
								<%= submit_tag "Unfollow", class: 'btn btn-danger' %>
							</div>
						<% end %>
					<% else %>
						<%= link_to "Follow", new_user_follow_path(followed_user_id: @user.id), :class => "btn btn-primary ", id: 'add-follow', data: { user_followed_id: @user.id.to_param } %>
					<% end %>
				</div>
			<% end %>


		</div>

	</div>





<% if current_user.id == @user.id %>
<br>
<%= link_to "Edit Account", edit_user_registration_path, :class => "btn btn-warning" %>
<% else %>
<% end %>

<br>
<br>

<% if @questions_answered.count > 0 %>
<div class="row">
  <div class="col-md-7">

    <div class="page-header">
      <h1>Views</h1>      
    </div>

			<% @questions_answered.each do |question| %>
            <h3><%= link_to question.title, question_path(question, user_id:@user.id) %></h3>
            <br>
			<% end %>

		</div>
				</div>
<% end %>