config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :points
    resources :answers
  end

  resources :user_follows

  resources :activities, only: [:index]

  root 'questions#index'

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users, only: [:show]
  post 'users/update_activities_last_viewed'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>













<head>
  <title>Wurldview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <%= link_to root_path, :class => 'navbar-brand' do %> <span class="glyphicon glyphicon-fire" style="width:40px; height:36px; font-size:36px;"></span> <% end %>
        <ul class="nav navbar-nav navbar-right ">
          <% if user_signed_in? %>
            <li id="activity-feed"><%= link_to activities_path, :class => "button small-button green-button" do %><span class="glyphicon glyphicon-asterisk" style="width:40px; height:36px; font-size:36px;"></span><% if current_user.activities_count > 0 %><span class="badge"><%= current_user.activities_count %></span><% end %><% end %></li>


          <% else %>
          <% end %>

        <li class="dropdown">
          <% if signed_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><img src=<%= current_user.twitter.image%> class="img-circle" alt="" style="width:36px;height:36px;border:0"> <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">

            







            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><a href="https://www.facebook.com/groups/1855556068002004/">Requests / Suggestions</a></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>

          <% else %>

          <li><a href="/users/auth/twitter"><span class="glyphicon glyphicon-log-in" style="width:40px; height:36px; font-size:36px;"></span></a></li>


          <% end %>
        </li>



        </ul>


     </div>
  </nav>

  <div class="container" id="main-content-container">
    <% flash.each do |type, message| %>
          <div class="alert <%= flash_class type %>">
        <%= message %>
          </div>
        <% end %>

    <% if signed_in? %>
      <%= javascript_tag do %>
        window.currentUserId = '<%= current_user.id %>';
      <% end %>

    <% end %>


    <%= yield %>
  </div>
  <%= yield :footer %>

</body>

<script id="activities-template" type="text/x-handlebars-template">

  <%= link_to activities_path, :class => "button small-button green-button" do %> <span class="glyphicon glyphicon-asterisk" style="width:40px; height:36px; font-size:36px;"></span>{{#ifCond count}}{{else}}<span class="badge">{{count}}</span>{{/ifCond}}


   <% end %>

</script>


</html>